language: minimal

branches:
  only:
    - master

git:
  depth: 1
  
services:
  - docker

install:
  - make devenv

script:
  - make

deploy:
  - provider: script
    script: make deploy GITHUB_REPO_TAG="$TRAVIS_TAG"
    skip_cleanup: true
    on:
      tags: true
